version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: compilex-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: compilex
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - compilex-network

  # Backend API
  backend:
    build: ./backend
    container_name: compilex-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/compilex?authSource=admin
      JWT_SECRET: your-super-secure-jwt-secret-change-this
      CORS_ORIGIN: http://localhost
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - compilex-network
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build: ./frontend
    container_name: compilex-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - compilex-network

volumes:
  mongodb_data:

networks:
  compilex-network:
    driver: bridge
